web:
 image: rociiocs/seibi-experience
 ports:
  - "8443:8443"
 environment:
  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
  - spring.jpa.hibernate.ddl-auto=create
 links:
  - db
  - serv

web2:
 image: rociiocs/seibi-experience
 ports:
  - "8444:8443"
 environment:
  - server.port=8443
  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
  - spring.jpa.hibernate.ddl-auto=create
 links:
  - db
  - serv

db:
 image: mysql
 environment: 
  MYSQL_ROOT_PASSWORD: seibi1234

serv:
 image: rociiocs/seibi-experience-services
 ports:
  - "8080:8080"

